import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // Icons generated by users
  icons: defineTable({
    userId: v.string(),
    prompt: v.string(),
    model: v.optional(v.string()),
    sourceName: v.optional(v.string()),
    storageId: v.id("_storage"),
    createdAt: v.number(),
  }).index("by_user_createdAt", ["userId", "createdAt"]),

  // Keep the existing messages table referenced by convex/messages.ts
  messages: defineTable({
    author: v.string(),
    body: v.optional(v.string()),
    createdAt: v.optional(v.number()),
  }).index("by_author", ["author"]),
});


